### ISSUE TITLE
Question regarding using pre-trained models.

### ISSUE THREAD

**Issue by NIRVANALAN** [facebookresearch/banmo#12]
Dear GengShan,
Hi! I am trying to use your pre-optimized models for evaluation. Unfortunately when I call the scripts, it says
```
FATAL Flags parsing error: ERROR:: Unable to open flagfile: [Errno 2] No such file or directory: 'tmp/cat-pikachiu/opts.log
```
I don't know how the arg-parsing works for the ```absl``` system and do you have any suggestions to bypass the need of opts.log?

Thanks.

**Comment by NIRVANALAN** [comment]
ok, I rerun the optimization script and copy the opts.log to the tmp folder then it works.

**Comment by YuhsiHu** [comment]
Thank you for your sharing! So we need to first  run command in optimization before we try optimized-model? What did optimization do to the model?

**Comment by gengshan-y** [comment]
Updated the repo to fix this issue. It should work without running optimization now.
