### ISSUE TITLE
no camera path and keypoints.json in database

### ISSUE THREAD

**Issue by JaphiaChen** [facebookresearch/banmo#14]
In I/O.py, you have variables 'rtklist' and ‘kplist’ which contain paths like 'database/DAVIS/Cameras/Full-Resolution/cat-pikachiu00/00000.txt' and 'database/DAVIS/KP/Full-Resolution/cat-pikachiu00/00000_keypoints.json'. But there are no relative files found after unzipping the dropbox files.

**Comment by gengshan-y** [comment]
Apologies for the confusion. `kplist` is never access in the codebase. `rtklist` is only referred to when external root poses are provided. See [this note](https://github.com/facebookresearch/banmo/tree/main/scripts#example-known-root-poses) for using external poses.

If no external camera poses are provided, banmo will estimate from a pre-trained pose network.

**Comment by JaphiaChen** [comment]
thanks!
