### ISSUE TITLE
hi，can banmo be used for 3D reconstruction of cars？ 

### ISSUE THREAD

**Issue by yushengjiexy** [facebookresearch/banmo#15]
<img width="806" alt="image" src="https://user-images.githubusercontent.com/63044657/172146276-856d2f86-fcea-4145-b7a9-4e3d135e28e4.png">

**Comment by yushengjiexy** [comment]
Thanks for your reply！
When you say rough camera viewpoints, do you mean the camera's own position or the car's position in the camera's view？

**Comment by gengshan-y** [comment]
The input viewpoint/pose is defined as 
`P_camera = R P_canonical + T`
where `(R T)` is the rigid transformation that transforms 3D points in the object canonical coordinates to the camera coordinates. We use opencv coordinate systems (x-right, y-down, z-forward). To convert from opengl format, you want to take the negative value of y and z coordinates. 

Let me know if there are other questions.

**Comment by yushengjiexy** [comment]
sorry, I am a beginner, my question is more basic.
Can you explain what the object canonical coordinate is, or provide me with some papers? Is the object canonical coordinate  similar to the world coordinate, or is the object coordinate fixed on the object moving with the object?
Thank you very much!

**Comment by gengshan-y** [comment]
I see, [this](http://www.codinglabs.net/article_world_view_projection_matrix.aspx) might help -- by canonical coordinate, I mean the model space. It's the coordinate system attached on the object.

**Comment by yushengjiexy** [comment]
Thank you！
I have no further questions for the time being. I'm going to do it now. Thank you for your guidance.
