### ISSUE TITLE
some problems when i try pre-optimized models according to the suggestion

### ISSUE THREAD

**Issue by yushengjiexy** [facebookresearch/banmo#16]
When I enter “bash scripts/render_nvs.sh 0 $seqname tmp/cat-pikachiu.pth 5 0”, the following log comes out. The error causes the command to exit abnormally.I am sorry to bother you again.

-------------------------------logs--------------------------------------------------------------------
![screenshot_1](https://user-images.githubusercontent.com/63044657/173825510-1c108240-72aa-441c-9506-00ecf202d2f2.png)

I have uploaded the logs to the attachment.
[Untitled 2.odt](https://github.com/facebookresearch/banmo/files/8909148/Untitled.2.odt)
--------------------------------command--------------------------------------------------------------------

![screenshot](https://user-images.githubusercontent.com/63044657/173823690-74e864dc-544d-483a-a637-4701a4759c3e.png)

**Comment by gengshan-y** [comment]
This is the first error: 
```
CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

Can you make sure pytorch is properly installed?

**Comment by yushengjiexy** [comment]
i think i have properly install pytorch.
![image](https://user-images.githubusercontent.com/63044657/173978906-16782187-4590-4d3c-a43a-b8d4eb34630f.png)

this error may cause by .....

I guess that there are some problems with the dataset i download.

**Comment by yushengjiexy** [comment]
i think i have properly install pytorch.
![image](https://user-images.githubusercontent.com/63044657/173978906-16782187-4590-4d3c-a43a-b8d4eb34630f.png)

this error may cause by .....

I guess that there are some problems with the dataset i download.

**Comment by yushengjiexy** [comment]
hi, i solve this porblem by create virtual environment [B. torch1.7+cu110].
but, when i run "bash scripts/render_mgpu.sh 0 $seqname tmp/cat-pikachiu.pth "0 5" 64", it show this:
![image](https://user-images.githubusercontent.com/63044657/174074253-8149c764-0c4b-4b4c-aeb8-bd41d18ae7f7.png)

**Comment by yushengjiexy** [comment]
this is the logs.
[Untitled.2 (1).odt](https://github.com/facebookresearch/banmo/files/8919008/Untitled.2.1.odt)

**Comment by gengshan-y** [comment]
Feel free to ignore this warning, as long as there are files `ls tmp/*all.mp4`

**Comment by yushengjiexy** [comment]
hhh,ok,tks!
