### ISSUE TITLE
 I failed to run  “template-short.sh“

### ISSUE THREAD

**Issue by yushengjiexy** [facebookresearch/banmo#17]
It seems to be a data set problem

![image](https://user-images.githubusercontent.com/63044657/174428011-a189cda8-7cc5-4f9c-98b3-a95b1d377a74.png)

**Comment by yushengjiexy** [comment]
All the logs are here. For the convenience of debugging, I only reserved the dataset processing of cat-pikachiu01. It is the same error when process the entire dataset. Sorry to bother you again.

**Comment by gengshan-y** [comment]
Did you run image to line conversion?
`python preprocess/img2lines.py --seqname cat-pikachiu``
If so, there should be data under `Pixels` folder.

**Comment by yushengjiexy** [comment]
Thank you. I solved the problem
