### ISSUE TITLE
Qusetion about the Caluculation of the Mahalanobis Distance

### ISSUE THREAD

**Issue by MayuOshima** [facebookresearch/banmo#18]
Hello, thanks for your great work!
I have one question.
In
https://github.com/facebookresearch/banmo/blob/2bf3c0a4974b73bc4a044b4bf19b812e0f6b2f77/nnutils/geom_utils.py#L237
and
https://github.com/facebookresearch/banmo/blob/2bf3c0a4974b73bc4a044b4bf19b812e0f6b2f77/nnutils/geom_utils.py#L238
when you are calculating Mahalanobis Distance, what are you doing here?
Why mdis need to first multiply 100 and log_scale.exp() and then (-10 * mdis.sum(3))?
What is the log_scale from skin_aux?

Thanks! :)

**Comment by gengshan-y** [comment]
Hi, the code is cleaned up a bit. Hopefully it's more clear. https://github.com/facebookresearch/banmo/blob/6ce2b0cbaa3f9552bcfeee17555ecf54111889b7/nnutils/geom_utils.py#L232-L234

**Comment by MayuOshima** [comment]
Thank you for your quick reply!
But I still have three questions, sorry.

1. How did you find the number 1000 to make the weight more concentrated? I mean, why you didn't use other numbers like 100, 2000, for example;
2. What is the global temporature scaling? I have Googled that but it seems there is not enough information about this term.
3. Given a mesh, how to get log_scale? If I guess right, it is an inherent attribute of a given mesh, right?

**Comment by gengshan-y** [comment]
Thanks for the follow up. https://github.com/facebookresearch/banmo/blob/26156475e2c464141c1e9a810ca265e6eb976afe/nnutils/geom_utils.py#L232-L235

To understand the temperature parameter better, perhaps [this](https://jdhao.github.io/2022/02/27/temperature_in_softmax/) will help

1. The factor 1000 is empirically chosen by looking at the resulting skinning weights. 1000 produces skinning weights that has a clear separation between bones. This gives a good starting point for optimization. 
2-3. log_scale is a scalar parameter initialized as 0 and converges to ~1.5.
