### ISSUE TITLE
batch load or line load

### ISSUE THREAD

**Issue by s0rrymaker77777** [facebookresearch/banmo#21]
Hi Gengshan,

Thank you so much for your great work.

I noticed that you use batch_load for evaluation and line_load for training in BANMo. I want to learn information from the whole image, so I try to use batch_load in training, but the performance will be degraded compared to the original line_load training. Do you have any suggestions? Thanks a lot!!

**Comment by gengshan-y** [comment]
When switching to `--batch_load`, you want to change `--nsample` (number of sampled pxs per image) as well.
For instance, `--batch_size 8 --nsample 128`, which ensures the same total number of sampled pixels.

Note you are expected to still see slightly worse shape and camera poses, given the total number of updated cameras per iter is fewer than `--line_load`. My hunch is using CNN to parameterize cameras will improve results in this case, as in [LASR](https://openaccess.thecvf.com/content/CVPR2021/papers/Yang_LASR_Learning_Articulated_Shape_Reconstruction_From_a_Monocular_Video_CVPR_2021_paper.pdf).

**Comment by s0rrymaker77777** [comment]
Thank you for your prompt reply! I found nsample is 6 when batch_size is 256. So how to calculate the related nsample when batch_size changes? Thanks!

**Comment by gengshan-y** [comment]
So `nsample * batch_size` gives you the total number of pixels sampled in a batch, which should roughly stays the same

**Comment by kts707** [comment]
Hi @s0rrymaker77777 , what `--nsample `and `--batch_size` did you use to get the similar performance as `--lineload`? 

Also I tried to switch to batch load with `--nsample 128 --batch_size 12` to make sure `nsample * batch_size` stays the same as in lineload, however the training is extremely slow compared to line load. Did your batch load training also become very slow?

**Comment by gengshan-y** [comment]
If I remember correctly, `--nsample 192 --batch_size 8` is 1.5-2x slower and gives slightly worse performance.

**Comment by kts707** [comment]
Thanks!
