### ISSUE TITLE
About the 2D keypoint transfer metric

### ISSUE THREAD

**Issue by phamtrongthang123** [facebookresearch/banmo#24]
Hi, thanks for publishing this wonderful code.

I want to ask that is it possible to evaluate the reconstructed 3D model using the 2D keypoint transfer metric defined in ViSER and LASR? Because BANMo has the ability to register the correspondences between frames so I thought it is possible. But because in the main paper you use Chamfer distance instead of 2D keypoint transfer, so I am also wondering why we can't use 2D keypoint transfer metric, is it inappropriate in this case? 
Thank you very much.

**Comment by gengshan-y** [comment]
Hi, there are pros and cons for both the (a) 2D keypoint transfer metric in LASR/ViSER and (b) 3D error in banmo.
- In terms of data diversity/scale (a) can be easily annotated on real data but (b) is difficult to get at scale.
- In terms of faithfulness, (a) only cares about 2D correspondence, and leaves room for "cheating" in 3D  (b) directly reflects 3D accuracy.

Banmo uses (b) but (a) has its merits as well.
