### ISSUE TITLE
Adaptation to a new video

### ISSUE THREAD

**Issue by s0rrymaker77777** [facebookresearch/banmo#25]
Hi, thanks for your work!

I am trying to adapt a pre-trained model to a new video. But if I did not use template-prior-model.sh and just used the pre-trained model, I cannot load cameras from init-cam. The camera parameters will be wrong. Do you have any suggestions if I do not want to retrain the pre-trained models? Thanks!

**Comment by gengshan-y** [comment]
Hi, I don't fully understand the question. Do you want to use the pre-trained cat model or not? Could you elaborate the setup (input/output/constrains)?

**Comment by s0rrymaker77777** [comment]
Hi, 

For example, I use the adult7 pre-trained model on a new video without running template-prior-model.sh. The input is following your pre-process raw videos into banmo format. The output is upside down, I think it can be caused by the missing of init-cam folder. And the reconstructed human model is still same as adult7 and does not reconstruct the human in new videos. Thanks.

**Comment by gengshan-y** [comment]
If I understand correctly, you want to run feedforward inference on a new video. Unfortunately, banmo is not able to do that. Similar to NeRF/differentiable rendering, we solve an optimization problem on a set of test videos. This means you have to run optimization again even with some pre-trained weights.

**Comment by s0rrymaker77777** [comment]
Got it, thanks!
