### ISSUE TITLE
Problems about synthetic data

### ISSUE THREAD

**Issue by Iven-Wu** [facebookresearch/banmo#3]
Hi. I'm trying to use the synthetic generator. I want to know what's the unit of the focal length and depth in render_synthetic.py?

**Comment by gengshan-y** [comment]
Assuming you know the desired pixel focal length, then 
```
args.focal = 2 * focal length (px) / args.img_size (px).
```
Also see [here](https://github.com/facebookresearch/banmo/blob/ff5df1d4df78a681fbde06b214a6d1b1c89f8829/scripts/synthetic/render_synthetic.py#L115).

Input object mesh is [normalized to unit size](https://github.com/facebookresearch/banmo/blob/ff5df1d4df78a681fbde06b214a6d1b1c89f8829/scripts/synthetic/render_synthetic.py#L65) (-1,1), and depth is in the same unit of the normalized mesh.

**Comment by Iven-Wu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Iven-Wu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
