### ISSUE TITLE
Question about CSE and root pose

### ISSUE THREAD

**Issue by DummyNodeHead** [facebookresearch/banmo#32]
Hi there! Thanks for sharing this amazing work!

I have been reading your work for many days and I'm still confused about CSE:

1. You have shown the good result of hand, eagle, laikago robot. Did you apply the CSE model trained for quadruped animals to these non-quadruped objects? If not, how did you train the CSE model for these objects? (especially for hands) Did you modify the dataset of hands so that it can be used to training CSE?
2. Like what you said in [CSE embedding for other object categories](https://github.com/facebookresearch/banmo/issues/26) and [banmo for reconstruction of cars](https://github.com/facebookresearch/banmo/issues/15), Does it mean that if I want to reconstruct a rigid object such as a cup or a car, I could get good results as long as a good enough initial root pose of it is given? So CSE and PoseNet are not necessary as long as I can get a good root pose by other means?

Any response will be greatly appreciated!

**Comment by DummyNodeHead** [comment]
Thanks for your response!

So during the registration, the same pre-trained quadruped CSE model is used to get canonical embeddings of the image, and is optimized with the MLP that get the embeddings of the 3D vertex jointly?
And I'm a little confused about [this line](https://github.com/facebookresearch/banmo/blob/1d022945be987a601a36a25c27e71a8c06008bef/nnutils/banmo.py#L1334). What do csenet_feats and dps refer to respectively?

**Comment by gengshan-y** [comment]
`csenet_feats` is the 112x112x16 feature map, and `dps` is the 112x112 integer vertex index to the canonical mesh (used in CSE) for visualization only.

The script for CSE finetune is not published given all the results we've shown in the paper did not fine-tune CSE. But the functions are in this repo. To fine-tune CSE, you may need to pass `--ft_cse ` and `--nolineload --batch_size 8 --nsample 128`. The later flags makes sure the whole image is loaded to compute CSE features.
