### ISSUE TITLE
left multiply or right multiply?

### ISSUE THREAD

**Issue by Lxiangyue** [facebookresearch/banmo#33]
Thanks for your great work!

May I ask why you sometimes apply left multiply on Rmat, and sometimes right multiply? Why not use the same formation? What's the difference? I'm really confused about that.

**Comment by gengshan-y** [comment]
Hi, thanks for pointing it out. There should only be left multiply in the ideal case (`P'=RP+T` assuming P is 3xN). But sometimes P is Nx3, in this case, I right multiply R transpose (`P'=PR^T+T`), which is equivalent to left multiplying R. Hopefully there is no exceptions, if there is please let me know.

**Comment by Lxiangyue** [comment]
Thanks for your clear reply! It seems that they are equal. And the attention point is using R transpose instead of R when utilizing right multiply.
