### ISSUE TITLE
About the fraction occupied

### ISSUE THREAD

**Issue by Xiuxiu97** [facebookresearch/banmo#35]
Hi, thanks for your great work. 

I want to ask about the meaning of the fraction occupied. Could you please introduce the relationship between the fraction occupied and the quality of the reconstructed result? It doesn't look like the smaller the better. Thanks!

**Comment by gengshan-y** [comment]
It shows how much the sampled 3D locations are "occupied". This is only used for reference and does not have a strong correlation with the reconstruction quality. However, a too smaller values means you reconstructed shape is mostly empty, which is not desired.

**Comment by Xiuxiu97** [comment]
Thanks for your reply!
