### ISSUE TITLE
Training BANMo using my own videos

### ISSUE THREAD

**Issue by Xiuxiu97** [facebookresearch/banmo#37]
Hi, thanks for your work!

I try to train BANMo using my own videos, I preprocess the videos as you instructed. However, when I see the segmentation results in DAVIS/Annotations, the results seem not to be preprocessed like adult7 and cat-pikachiu. Like the following image, there are different colors on the cat. When I check my own videos, there is only one color and the detection result is not good. Did I miss something? Thanks!
![vis-00097](https://user-images.githubusercontent.com/110981717/194552586-c7404589-67b9-4b94-b3fc-f70b6d40c1b8.jpg)

**Comment by gengshan-y** [comment]
Hi, the detection pipeline in the repo is the one I used to generate the preprocessed data, besides some difference in color visualization. To get a better color vis, [here](https://github.com/facebookresearch/detectron2/issues/3457) is some discussion in the original densepose repo. I can look further if you post the bad results.

**Comment by Xiuxiu97** [comment]
Hi, as shown in the following, I preprocess cat-pikachiu with the raw data (the second one), the bounding box is always not correct and the color does not look like the preprocessed data. What does the different color mean in the shown video (the first video)?
 

https://user-images.githubusercontent.com/110981717/194700403-dc22ffcf-218c-4980-a68c-9d0ca0f4ed7f.mp4


https://user-images.githubusercontent.com/110981717/194700422-1944d675-ef81-43ea-9eeb-45dbe159f7c4.mp4

**Comment by gengshan-y** [comment]
The bbox on the cat is correct as far as I can see. The bbox on other categories are automatically filtered and not used for reconstruction.

The vis in the proposed data is a densepose visualization that I posted in the first reply.

Let me know if this does not answer your question.

**Comment by Xiuxiu97** [comment]
Hi, as shown in the second video, the bounding box always has a bit more on the top and right. This happens in all videos.

**Comment by gengshan-y** [comment]
You are right, this is a separate visualization bug. [This line](https://github.com/facebookresearch/banmo/blob/1d022945be987a601a36a25c27e71a8c06008bef/preprocess/mask.py#L105) should be replace by
```
    outputs.pred_boxes.tensor[:,:2] -= pad
    outputs.pred_boxes.tensor[:,2:] -= 2*pad
```

I don't think this affects reconstruction though. Thanks for the catch. Will update the repo.

**Comment by Xiuxiu97** [comment]
Hi, I have tried the code, the second line may also be -= pad. Thank you very much!
