### ISSUE TITLE
Question about mesh of Viser in Banmo

### ISSUE THREAD

**Issue by bravotty** [facebookresearch/banmo#43]
Thank you for your extremely good work.
I had a question reproducing viser in that the mesh generated for the cat was smoother but poorly shaped than the mesh you put in the banmo. (Compare below, left is the mesh in banmo, right is the mesh I reran viser to generate)
![image](https://user-images.githubusercontent.com/37895431/199428082-c3ed2717-2b72-4d6d-8a62-598d167fe5b1.png)
As well as in ama-female, and the one we generated would tend to have no hands (as shown in the comparison below)
![image](https://user-images.githubusercontent.com/37895431/199428504-9076ba64-eb11-416e-9f37-728b26520c21.png)
The images above are all n_faces=8000 in the code and are fully trained by the official viser script.

**Comment by gengshan-y** [comment]
Hi, the comparison with viser in the paper was run with a lower weight on the laplacian smoothness term (`triangle_reg_wt=0.005`). The latest viser codebase uses `triangle_reg_wt=0.025` to produce more visually appealing but smoother result.

You should be able to get the same result as we showed in the paper with [triangle_reg_wt=0.005](https://github.com/gengshan-y/viser-release/blob/1ee3ca6e3d61c856ec65f08b9d1a4b46a56318c6/nnutils/mesh_net.py#L92)

**Comment by bravotty** [comment]
Thank you for your reply and I will make the relevant improvements.
