### ISSUE TITLE
Optimized models on dropbox

### ISSUE THREAD

**Issue by HugoNTL** [facebookresearch/banmo#47]
Thanks for your great work!
I would like to download the optimized models from your dropbox.
However, it shows that the files are deleted.
May I know if you can re-upload the optimized models again?
For example:
https://www.dropbox.com/s/qzwuqxp0mzdot6c/cat-pikachiu.npy
https://www.dropbox.com/s/dnob0r8zzjbn28a/cat-pikachiu.pth

**Comment by gengshan-y** [comment]
Hi, thanks for letting me know! Those are accidentally deleted and should be restored now.

**Comment by HugoNTL** [comment]
Thanks for your help! It works well now.
