### ISSUE TITLE
some problem with colab demo

### ISSUE THREAD

**Issue by dangdang2222** [facebookresearch/banmo#55]
Thanks for your great job.
When I run the third block of provided colab demo, there has some problem and i can't solve it. 
Any advice for me, please

<img width="894" alt="image" src="https://github.com/facebookresearch/banmo/assets/64007947/3e0fbe97-70f5-45a5-bf4f-9e7854d2b948">

**Comment by gengshan-y** [comment]
https://github.com/graspnet/graspnet-baseline/issues/47#issuecomment-1326158443

You may try `pip install trimesh==3.15.1 `
