### ISSUE TITLE
can banmo be used for 3D reconstruction of birds？

### ISSUE THREAD

**Issue by litchisea** [facebookresearch/banmo#56]
Thank you for your fascinating work!
Birds are neither human nor four-legged, is it possible to have a bird
Pre-trained PoseNet weights, or can the PoseNet weights trained for quadrupeds be modified for 3D reconstruction of birds?

**Comment by litchisea** [comment]
Thank you so much! Can the pre-trained model of Eagle on simulated data be used for Eagle on real data? If yes, can you provide the pre-trained model of Eagle?

**Comment by gengshan-y** [comment]
Hi, the pre-trained weights only store the shape and pose of a deformation 3D object, and cannot be used to infer pose/shape from images. To do so, one solution is to further train a feedforward network given those weights (e.g., in our recent work [dasr](https://github.com/jefftan969/dasr))

**Comment by litchisea** [comment]
Thank you very much!
