### ISSUE TITLE
Confused about the data flow

### ISSUE THREAD

**Issue by qq456cvb** [facebookresearch/banmo#57]
Hi, first thanks for sharing your code. I have been reading the code for a couple of days and fail to figure out how the data is sent to the model at training time. Here are some findings:

There is a `forward_default` and `forward_warmup_*` in `banmo.py` and they all ignore the input `batch` arguments. Taking a deeper look at the function `train` function, I find that before each `train_one_epoch`, there is a `self.eval()` which calls `render_vid`, and it finally calls `model.set_input`. 

`set_input` will call either `convert_batch_input` or `convert_line_input`, both of which sets `batch['img']` to `self.imgs`. And `self.imgs` together with other attributes will be used in `forward_default` function. Then the question is that `batch` comes from `eval->render_vid`, where it sets the batch filled up with data from `self.evalloader` with data index from `np.linspace` on L455. This is confusing, it seems that every training batch is given by the data (w/o randomness) from `eval` dataset with certain dataset index like `[0, len(data) / 8, 2 * len(data) / 8, ....]`. Is it on purpose or did I miss something?

**Comment by gengshan-y** [comment]
Hi, to clarify a few things:
- self.eval() is not for training. It is called every 200 iterations to visualize mesh, rendering etc.
- forwarda_default() is the forward function that is called every for training iteration. However, the `batch` argument is [not ignored](https://github.com/facebookresearch/banmo/blob/d2ac32470c1cfb2542f354ac4024403509409df6/nnutils/banmo.py#L460-L463).
- by default, convert_line_input(...) loads pixels and is used at training time; convert_batch_input(...) loads full images and used for the self.eval() routine

At train time
- [data=>training loop](https://github.com/facebookresearch/banmo/blob/d2ac32470c1cfb2542f354ac4024403509409df6/nnutils/train_utils.py#L903) 
- [training loop => model.forward_default(...)](https://github.com/facebookresearch/banmo/blob/d2ac32470c1cfb2542f354ac4024403509409df6/nnutils/train_utils.py#L934)
- [model.forward_default(...) => model.imgs, model.masks,....](https://github.com/facebookresearch/banmo/blob/d2ac32470c1cfb2542f354ac4024403509409df6/nnutils/banmo.py#L1460-L1463)
- then {model.imges, model.masks,...} are passed into the rendering function to [compute reconstruction losses](https://github.com/facebookresearch/banmo/blob/d2ac32470c1cfb2542f354ac4024403509409df6/nnutils/rendering.py#L515)

**Comment by qq456cvb** [comment]
Thank you very much for the clarification! It makes the code structure more clear now.
