### ISSUE TITLE
export animatable glTF

### ISSUE THREAD

**Issue by LyndzP** [facebookresearch/banmo#58]
Hello,

Thank you so much for your wonderful work on this project! I've been trying to convert the deformable banmo output into glTF format.

After discovering issue #46, I've been learning about the structure of glTF and skinning weights, but I still find myself at a loss when it comes to exporting to glTF.

Could you perhaps share some insights on how to export to an animatable glTF? Which libraries did you use to accomplish this? I've been experimenting with Blender's Python API, but I am still making static mesh.

Additionally, do you happen to have an ETA for when the code for exporting to glTF might be shared?

Thank you very much for your time and help. I greatly appreciate it!

**Comment by gengshan-y** [comment]
Hi, I wrote some [utility functions ](https://gist.github.com/gengshan-y/d0699c3c37063a56939198e6523cd069) and [scripts](https://gist.github.com/gengshan-y/939b50bf84c18dc467793891e0fd56c7) to do the conversion. Hope it can help a bit, although it is likely those would not work out of the box for this repo. 

The plan is to integrate the gltf conversion to our new repo [lab4d](https://github.com/lab4d-org/lab4d) in a few weeks after I finish another code release task.

**Comment by LyndzP** [comment]
Thank you so much for your detailed explanations and guidance. They have helped me immensely in successfully writing code to apply skinning weights to glTF. I'm truly grateful for your help.

However, I'm currently facing a problem. I am trying to understand how to obtain a "urdf object of the ragdoll." From my understanding, it seems like there is a certain sequence or hierarchy involved in the relationship between the bones, likely pertaining to the parent node. However, I'm still not entirely sure about this.

The related code is as follows: 
```
    if urdf is not None:
        gltf.nodes[1].children = []
        bone_rtks_local = []
        # go through all joints and find parents
        for idx, parent_idx in enumerate(urdf.parent_idx):
            # forward kinematics
            # G(xo-xt) = [G(xo-xt''')] [G(xo-xt''')^-1 ... G(xo-xt')] [G(xo-xt')^-1 G(xo-xt)]
            # update topology
            gltf.nodes[parent_idx+2].children += [idx+2]
            if parent_idx>=0:
                # update rest pose
                global_ga = np.eye(4); global_ga[:3,:3] = rest_rot[parent_idx]; global_ga[:3,3] = rest_trn[parent_idx]
                global_gb = np.eye(4); global_gb[:3,:3] = rest_rot[idx];        global_gb[:3,3] = rest_trn[idx]
                local_g = np.linalg.inv(global_ga)@global_gb
                gltf.nodes[idx+2].rotation = R.from_matrix(local_g[:3,:3]).as_quat().tolist()
                gltf.nodes[idx+2].translation = local_g[:3,3].tolist()
                # update deformed pose
                bone_rtk_local = np.linalg.inv(bone_rtks[:,parent_idx]) @ bone_rtks[:,idx]
            else:
                bone_rtk_local = bone_rtks[:,idx]
            bone_rtks_local.append( bone_rtk_local )
        bone_rtks = np.stack(bone_rtks_local,1)
```
 Could you possibly provide some insight into this issue? I deeply appreciate your time and assistance

**Comment by gengshan-y** [comment]
Sorry for the very late reply, in case it still helps, the `urdf` object corresponds to `robot.urdf` in this [line](https://github.com/gengshan-y/rac/blob/0a5d4cca5037247228f6c2dd4a31d0e97de1ec89/nnutils/banmo.py#L373). 

`parent_idx` is a list of indices such as [-1, 0, 1, 2, 3] (represents a kinematic chain; for quick reference, the quadruped skeleton is exported to lab4d at [here](https://github.com/lab4d-org/lab4d/blob/545a56ff1eace1ebe19a383c42d13a62ae234811/lab4d/utils/skel_utils.py#L226-L252)). Each element points to the parent node, as computed [here](https://github.com/gengshan-y/rac/blob/0a5d4cca5037247228f6c2dd4a31d0e97de1ec89/nnutils/urdf_utils.py#L12-L41).


The template-simp.gltf can be found [here](https://gist.github.com/gengshan-y/aee463100c56cc2d146b6da62f7e87d8)

**Comment by LyndzP** [comment]
@gengshan-y  I've finally succeeded in creating a moving glTF. Thank you so much for your help!

**Comment by LyndzP** [comment]
@gengshan-y I've finally succeeded in creating a moving glTF. Thank you so much for your help!
