### ISSUE TITLE
Error running bash scripts/render_mgpu.sh for human-cap dataset on [B. torch1.7+cu110]

### ISSUE THREAD

**Issue by SamyakR99** [facebookresearch/banmo#61]
Hi Gengshan,

Thank you for the awesome work!

I faced the following error when running: bash scripts/render_mgpu.sh 0 $seqname logdir/$seqname-e120-b256-ft2/params_latest.pth  "0 1 2 3 4 5 6 7 8 9" 256

Error: 
-----------------------------------------------------------------------------------------------------------------------
libEGL warning: failed to open /dev/dri/renderD129: Permission denied

libEGL warning: failed to open /dev/dri/renderD129: Permission denied

Traceback (most recent call last):
  File "scripts/visualize/render_vis.py", line 538, in <module>
    main()
  File "scripts/visualize/render_vis.py", line 330, in main
    r = OffscreenRenderer(img_size, img_size)
  File "/home/ubuntu/anaconda3/envs/banmo/lib/python3.8/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/home/ubuntu/anaconda3/envs/banmo/lib/python3.8/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/home/ubuntu/anaconda3/envs/banmo/lib/python3.8/site-packages/pyrender/platforms/egl.py", line 177, in init_context
    assert eglInitialize(self._egl_display, major, minor)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 409, in __call__
    return self( *args, **named )
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 12289,
        baseOperation = eglInitialize,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x7f17c38924c0>,
                c_long(0),
                c_long(0),
        ),
        result = 0
)

[OUT FILE](https://drive.google.com/file/d/1zWXye0_5uWUiAH_mrK0E3Hdv5rnMZBlV/view?usp=sharing)
-----------------------------------------------------------------------------------------------------------------------

I tried solving it through this  [LINK](https://github.com/mkocabas/VIBE/issues/148#issuecomment-759261580)

[OUT FILE](https://drive.google.com/file/d/13SOMnJhe9FbEQwYQdlkK2Mf_zBRcznhV/view?usp=sharing)
-----------------------------------------------------------------------------------------------------------------------
After that I get the following error: 
[OUT FILE](https://drive.google.com/file/d/1JU7GdGjaoXyDZx6xwZ7loiyJyvbSFv5F/view?usp=sharing)

I could not find a good source to fix this problem. Can you please look into it. 
Thanks!

**Comment by gengshan-y** [comment]
Hi Samyak, I've never seen this issue. Seems it has trouble creating `OffscreenRenderer`. As this is related to [pyrender](https://github.com/mmatl/pyrender), you might want to make sure the basic pyrender function works, e.g.
```
from pyrender import OffscreenRenderer
r = OffscreenRenderer(viewport_width=640, viewport_height=480)
```

This issue seems more related to the error code you got: https://github.com/mmatl/pyrender/issues/7

**Comment by SamyakR99** [comment]
Hi Gengshan, 

Thank you for the reply, 
I tried what you said and it did not work. However, when I change my gpu, it worked fine. Maybe some hardware issues. 

I will close this issue. 
Thanks!
