### ISSUE TITLE
Running out of space when running AMA (Samba + Swing)

### ISSUE THREAD

**Issue by SamyakR99** [facebookresearch/banmo#63]
Hi Gengshan, 

We had another quick question.

We were running the code for AMA (Samba + Swing) dataset and ran out of space on the disk. 
Upon inspection we identified that the pixels folder used up a lot of space. We were wondering if there is a way to reduce the space usage (preprocessing has been completed, we face this issue during training).  

We would really appreciate your insights on this.

PS: We are only running Banmo on this instance and hence whole space is totally being occupied by banmo data. Additionally, we only have only the AMA dataset in all folders in the attached screenshot. 

<img width="591" alt="Screenshot 2023-08-26 at 3 55 52 AM" src="https://github.com/facebookresearch/banmo/assets/48352883/585665af-58f2-46e0-8d12-858df3937572">

**Comment by gengshan-y** [comment]
Hi, one way to reduce the space used by `Pixels` folder is to use a smaller image size or lower-precision data types.

When running
```
python preprocess/img2lines.py --seqname $seqname 
```
the default is cropping images to [512x512](https://github.com/facebookresearch/banmo/blob/d2ac32470c1cfb2542f354ac4024403509409df6/nnutils/banmo.py#L88) and storing with float32.

I experimented with 256zx256 (appending `--img_size 256`) and storing flow as float16 (`.astype(np.float16)`) / color as uint8 (`.astype(np.uint8)`, need to pre/post-multiply 255) (which are the most costly parts), and the performance did not degrade noticeably.

**Comment by SamyakR99** [comment]
Thank you, that was very useful. 

Closing the issue
