### ISSUE TITLE
Mesh generated on AMA-swing 

### ISSUE THREAD

**Issue by SamyakR99** [facebookresearch/banmo#65]
Hi Gengshan, 

A follow-up to the previous issue, I ran the AMA swing dataset with Banmo (deafult settings). I get the following result.
<img width="634" alt="Screenshot 2023-08-28 at 8 05 59 PM" src="https://github.com/facebookresearch/banmo/assets/48352883/1eec0eff-f64c-4dee-9c00-af1dcc9d7dfc">

However, the mesh generated by another person in the a closed issue 
<img width="1257" alt="Screenshot 2023-08-28 at 8 08 54 PM" src="https://github.com/facebookresearch/banmo/assets/48352883/2aee4a8b-b971-4fc9-95b7-8061aefc9f9c">

Shows the following result for swing 
<img width="364" alt="Screenshot 2023-08-28 at 8 10 08 PM" src="https://github.com/facebookresearch/banmo/assets/48352883/359e65d3-85e4-4018-8651-94db6627b37a">

Which has much better mean shape and we can clearly identify the women.
Could you please point out what would be causing this difference? 

In addition, I could not find the script for evaluation(chamfer distance).

**Comment by gengshan-y** [comment]
The first seems a rest mesh extracted by the training script, where a loose surface threshold is used during marching cubes, making the surface thicker than it is. 

The second image is from the mesh extraction script that extracts the 0 surface.
```
bash scripts/render_mgpu.sh 0 $seqname logdir/$seqname-e120-b256-ft2/params_latest.pth \
        "0 8" 256
```

Below is the eval script
<img width="881" alt="image" src="https://github.com/facebookresearch/banmo/assets/13134872/29f9b4ea-cc3d-4566-965a-43b8e4f58180">

**Comment by SamyakR99** [comment]
Thank you, closing the issue.
