### ISSUE TITLE
Error when rendering AMA-swing dataset

### ISSUE THREAD

**Issue by SamyakR99** [facebookresearch/banmo#67]
Hi Gengshan, 

I used the following code to render swing dataset. I also the ran the same for cat-pikachiu.

bash scripts/render_mgpu.sh 0 $seqname logdir/$seqname-e120-b256-ft2/params_latest.pth \
        "0 1 2 3 4 5 6 7 8 9" 256 

Running on cat-pikachiu dataset was smooth. However, I got the attached error with AMA-swing. 

It is possibly a path issue where it is unable to load the correct path for the mesh materials. 
Could it be because I changed the seqname from what you used? 

If its a path issue, can you please point me to the code file that is loading the mesh material, and also the location of the mesh material (I want to confirm if I ran the training part correctly to obtain all the meshes needed)

![image](https://github.com/facebookresearch/banmo/assets/48352883/6e589095-e522-4b9a-afa4-b12a698c18be)

Thank you!

Update: It generates the all.mp4 file in logdir. So I think it works. But I am not sure what caused the error of mesh material

**Comment by gengshan-y** [comment]
Hi Samyak, This is a warning of not being able to load the floor mesh (for cosmetic purposes), and can be safely ignored

**Comment by SamyakR99** [comment]
Oh okay, that is great, Thanks!
