### ISSUE TITLE
unable to load materials from: ./wood.obj.mtl

### ISSUE THREAD

**Issue by limaolin2017** [facebookresearch/banmo#68]
### when I run: bash scripts/template.sh, here are the following error messages:
unable to load materials from: ./wood.obj.mtl

**Comment by limaolin2017** [comment]
### My script is as follows:

cd ./banmo
eval "$(conda shell.bash hook)"

# Activate your conda environment
source /soft/easybuild/x86_64/software/Miniconda3/4.9.2/etc/profile.d/conda.sh
conda activate banmo-cu113

export LD_LIBRARY_PATH=/gpfs/home/mli/.conda/envs/banmo-cu113/lib/:$LD_LIBRARY_PATH


seqname="cat-pikachiu"

python preprocess/img2lines.py --seqname $seqname

bash scripts/template.sh 0,1 $seqname 10001 "no" "no"

bash scripts/render_mgpu.sh 0,1 $seqname logdir/$seqname-e120-b256-ft2/params_latest.pth \
        "0 1 2 3 4 5 6 7 8 9 10" 256

**Comment by gengshan-y** [comment]
Hi, this is a warning (that is expected to happen) and does not affect the final rendering results. Please feel free to ignore or suppress it.
