### ISSUE TITLE
nvs_iter.sh

### ISSUE THREAD

**Issue by limaolin2017** [facebookresearch/banmo#69]
When I want to run this command:

bash scripts/nvs_iter.sh 0 logdir/$seqname-e120-b256-init/
argv[1]: gpu id
argv[2]: path to the logdir

I can't find 'nvs_iter.sh'

**Comment by gengshan-y** [comment]
It is located at `scripts/visualize/nvs_iter.sh`

**Comment by limaolin2017** [comment]
OK, thank you so much!
