### ISSUE TITLE
Extracting root pose

### ISSUE THREAD

**Issue by samiragarwala** [facebookresearch/banmo#71]
Hi! Thank you for the great work. I wanted to extract the optimized root poses for one of the cat-pikachiu sequences and was wondering if there was a way that you would recommend to do that? Thank you!

**Comment by gengshan-y** [comment]
Hi! The easiest way to go is probably using the visualization script for root poses
```
python scripts/visualize/render_root.py --testdir path-to-the-log-dir
```

This script loads the optimized root poses at each checkpoint and visualizes them. You may find the `vars` corresponding to the latest checkpoint, then `vars["rtk"]`in [this line](https://github.com/facebookresearch/banmo/blob/5729659e1a4c5afe0d0dcb9fe23b1a6339d62832/scripts/visualize/render_root.py#L67) is a Tx4x4 matrix where the Tx3x4 component is the [R|T] matrix defined as object-to-camera transformation.
