### ISSUE TITLE
exporting 3D models with skinning

### ISSUE THREAD

**Issue by q-r-z** [facebookresearch/banmo#74]
Hi @gengshan-y 
Thank you for bringing the model to obtain 3D models with various visualizations. And I wonder how I could get the 3D model just shown on your project homepage in the attached image. I tried the scripts that you provided in the #58 but I could not find the corresponding skin_path and rest_bone. 

It would be great help if you could offer some hints.

<img width="608" alt="Screen Shot 2024-01-29 at 19 05 18" src="https://github.com/facebookresearch/banmo/assets/52146447/a505d475-e116-40b2-982c-0cb0fbcf2299">

**Comment by gengshan-y** [comment]
Sorry for the late reply, 

skin_path and rest_bone are exported when running extract.py. Specifically in save_output() function, I added [those lines](https://gist.github.com/gengshan-y/757f2f32ad4cbba494956893afda61ab#file-gistfile1-txt-L17-L23)

**Comment by gengshan-y** [comment]
Also need to add [this](https://gist.github.com/gengshan-y/8e84081fbd4ea61655d35013705211e4#file-gistfile1-txt-L213) line in nnutils/train_utils.py

**Comment by q-r-z** [comment]
Thank you for the reply, finally it could run exactly. But the new problem is that the skinning is in silver instead of the fur color that I need. Could you please give some hints on the item extracted from the fur color as the skinning weights?

**Comment by gengshan-y** [comment]
Setting --ce_color to False [here](https://github.com/facebookresearch/banmo/blob/422098726f4c42914f7881f43ab57ea2cff2b90e/nnutils/banmo.py#L140) when you extract the mesh after training will assign rgb color to the mesh.

Also note this silver color is the surface property of the mesh. It has nothing to do with skinning.

**Comment by q-r-z** [comment]
Thank you for pointing it out. It worked so perfectly now.
