### ISSUE TITLE
Can Banmo support torch 1.11+cu113?

### ISSUE THREAD

**Issue by limaolin2017** [facebookresearch/banmo#75]
What changes do I need to make if I want Banmo to support torch 1.11+cu113?

**Comment by gengshan-y** [comment]
Seems doable, what if you change [this line](https://github.com/facebookresearch/banmo/blob/422098726f4c42914f7881f43ab57ea2cff2b90e/misc/banmo-cu113.yml#L61C5-L61C47) to the corresponding version info of torch 1.11?
