### ISSUE TITLE
Ckpt Release

### ISSUE THREAD

**Issue by GloryyrolG** [facebookresearch/banmo#78]
Hi @gengshan-y @jhugestar et al.,

May I ask if the ckpt could be provided for better understanding? thx & best,

**Comment by gengshan-y** [comment]
Hi, ckpts are provided under pre-optimized models in [Demo](https://github.com/facebookresearch/banmo#demo).

The [colab notebook](https://colab.research.google.com/drive/1dQJn1vsuz0DkyRZbOA1SulkVQ0V1kMUP?usp=sharing) could  also be a good starting point.
