### ISSUE TITLE
Enhancing Mesh Quality and Texture in BANMo Extracted Models

### ISSUE THREAD

**Issue by LyndzP** [facebookresearch/banmo#81]
Hello gengshan-y, 
I would like to thank you for providing your code which has allowed me to conduct various tests. I am writing to ask another question that came to mind.
 I happened to see your GitHub profile picture and noticed that the rendering in MeshLab is very clear, allowing the cat's eyes and nose to be distinctly visible. 

However, the cat-pikachiu model I extracted using BANMo does not have a clear face.
 Is there a way to enhance the mesh quality to make features like the eyes, nose, and mouth visible, or to extract the texture in higher quality, similar to your profile picture? 

Thank you for taking the time to consider my question.

**Comment by gengshan-y** [comment]
Hi @LyndzP, I remember the most important factor of getting good texture was to use higher eikonal loss weight (wt = 0.1).

The 3d model you mentioned was produced by a slightly more recent codebase, [RAC/PPR](https://github.com/gengshan-y/rac). The solution that I'm pretty sure will work is start from the inference code of [RAC/PPR](https://github.com/gengshan-y/rac) and write a training script similar to [this](https://gist.github.com/gengshan-y/ebaae19548cd354e92a162ee24539da1).

 I would be happy to give more suggestions.
