### ISSUE TITLE
How to generate the canonical rest shape of 3d file that it have real skins? not only output canonical rest shape 

### ISSUE THREAD

**Issue by larsoncs** [facebookresearch/banmo#9]
thks

**Comment by gengshan-y** [comment]
To color extracted meshes with radiance/textures, you could pull the latest commit and add `--noce_color` to the following line of `./scripts/render_mgpu.sh`: https://github.com/facebookresearch/banmo/blob/9461679db34d2f79ef5c867456f54bac505d6cb5/scripts/render_mgpu.sh#L18

Example outputs:
![unnamed (8)](https://user-images.githubusercontent.com/13134872/159198804-ddae28f5-1f3c-4f11-a0d6-68541687c814.gif)
![unnamed](https://user-images.githubusercontent.com/13134872/159198807-2b92266f-bef8-4d40-8350-127be49d5a29.png)
![unnamed (1)](https://user-images.githubusercontent.com/13134872/159198810-30c3c2ba-237a-4970-bd05-22a6acda3d7c.png)
